# Please compile

global:
  # Modify these paths with 
  project_dir: /g/furlong/project/92_SPT4_SPT5/CUTnTag # Add the full path of project directory. This is the directory where you cloned the repo
  scratch_temp_dir: /scratch/dulja/CUTnTag # Add a personal scratch folder with the format: /scratch/"surname"/"project_name" (e.g. /scratch/forneris/Chip_CUTnTag_SpikeIn)
  config_dir: ../../../config
  envs_dir: ../../../config/envs
  fastq_dir: /data/fastq
  qc_dir: /analysis/qc
  bam_dir: /data/bam
  bw_dir: /data/bw
  macs2_dir: /analysis/macs2
  idr_dir: /analysis/IDR
  htseq_dir: /analysis/htseq
  DESeq_dir: /analysis/DESeq
  depletion_heatmap_dir: /analysis/depletion_heatmap
  depletion_quantification: /analysis/depletion_quantification

# CUTnTag_samples will include all samples in your study. Samples should be described by: line background (e.g. twi-iLEXY), antibody (e.g. tin), condition (e.g. Dark)
# The first condition (condition1 here) must to be the control condition. Use the same order across lines and antibodies
# The sample name needs to be the same of the fastq file without extentions and end. e.g. file    "filname_1.fastq.gz" --> "filname"


CUTnTag_samples:
  TimeCourse:
    SPT5:
      2-4h:
        - CUTnTag_SPT5_TimeCourse_2-4h_rep1
        - CUTnTag_SPT5_TimeCourse_2-4h_rep2
      6-8h:
        - CUTnTag_SPT5_TimeCourse_6-8h_rep1
        - CUTnTag_SPT5_TimeCourse_6-8h_rep2
      10-12h:
        - CUTnTag_SPT5_TimeCourse_10-12h_rep1
        - CUTnTag_SPT5_TimeCourse_10-12h_rep2
      14-16h:
        - CUTnTag_SPT5_TimeCourse_14-16h_rep1
        - CUTnTag_SPT5_TimeCourse_14-16h_rep2
      18-20h:
        - CUTnTag_SPT5_TimeCourse_18-20h_rep1
        - CUTnTag_SPT5_TimeCourse_18-20h_rep2



annotation:
  genome_fasta: /g/furlong/genome/D.melanogaster/Dm6/fasta/dm6.UCSC.noMask.fa
  bwa_index: /g/furlong/genome/D.melanogaster/Dm6/indexes/bwa/dm6.UCSC.noMask.fa
  chrsize_bed: /g/furlong/genome/D.melanogaster/Dm6/chrsizes/dm6.ucsc.chrom.sizes.bed

parameters_mapping:
  mapping:
    min_mapping_quality: 20   # Minimum mapping quality
    max_fragment_length: 2000 # maximum fragment length for mapping
  coverage_noSpikeIn:
    normalization_method: RPKM    # Normalization type for non spike-in bigwigs
    bin_size: 10              # bin size for output bigwigs
  fastq_screen:
    n_sequences: 1000000      # Numer of reads sampled from fastq files
    aligner: bowtie2          # aligner for fastq_screen (default bowtie2, other alignments require installation in config/fastq_screen.conf)
  samples_correlation:
    bin_size: 1000            # bin size for sample correlation
  spikeIn_bigwig:
    effective_genome_size: 125464728    # Mappable drosophila genome bases
    bin_size: 10              # bin size for output bigwigs
    correction_type: "exo"    # Type of correction for spike-in normalization. Must be one of: tot_reads, endo, exo, exo_by_tot

parameters_peak_calling:
  filter_bam_for_peak_calling:
    max_fragment_length: 300  # Maximum fragment length for peak calling. From exxperience, excluding large insert size reads inproves peak calling. Check that there are enough reads after filtering. 
  macs2:
    genome_size: 125464728    # Mappable genome bases
    q_value_cutoff: 0.01      # Needs to be relaxed for IDR
    input_format: BAMPE       # bam format (BAMPE for paired end)
  macs2_peak_expansion:
    size: 300                 # Summits enlargment before IDR
  

  