# Please compile:
#   line 11.    Project directory
#   line 12.    scratch_temp_dir
#   line 30-45. CUTnTag_samples scheme. Final scheme lenght will depend on the number of samples in your study
#   line 48-50. Set species. First species is endogenous, second exogenous. Use "Dmel" for Drosophila Melanogaster. Use "Dvir" for Drosophila Virilis. 
#               If you use other species set up the annotation files accordingly (fasta and chromosome sizes) in annotation. lines: 55-59
#   line 52-54. Set colours for conditions (will be used in plots). Use RGB codes. Same condition names as in CUTnTag_samples
#   line 62-99. Set any parameter for the pipelines. Defaults for Dmel are already set.

global:
  project_dir: /g/furlong/project/92_SPT4_SPT5/Depletion_CUTnTag # Add the full path of project directory. This is the directory where you cloned the repo
  scratch_temp_dir: /scratch/dulja/SPT5_spikein_CUTnTag/Depletion_CUTnTag # Add a personal scratch folder with the format: /scratch/"surname"/"project_name" (e.g. /scratch/forneris/Chip_CUTnTag_SpikeIn)
  config_dir: ../../../config
  envs_dir: ../../../config/envs
  fastq_dir: /data/fastq
  qc_dir: /analysis/qc
  bam_dir: /data/bam
  bw_dir: /data/bw
  macs2_dir: /analysis/macs2
  idr_dir: /analysis/IDR
  htseq_dir: /analysis/htseq
  DESeq_dir: /analysis/DESeq
  depletion_heatmap_dir: /analysis/depletion_heatmap
  depletion_quantification: /analysis/depletion_quantification

# CUTnTag_samples will include all samples in your study. Samples should be described by: line background (e.g. twi-iLEXY), antibody (e.g. tin), condition (e.g. Dark)
# The first condition (condition1 here) must to be the control condition. Use the same order across lines and antibodies
# The sample name needs to be the same of the fastq file without extentions and end. e.g. file    "filname_1.fastq.gz" --> "filname"

CUTnTag_samples:
  SPT5longLEXY_3-4h_1hdepletion:
    NELF:
      Dark:
        - SpikeInCUTnTag_NELF_SPT5longLEXY_3-4h_1hdepletion_Dark_rep1
        - SpikeInCUTnTag_NELF_SPT5longLEXY_3-4h_1hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_NELF_SPT5longLEXY_3-4h_1hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_NELF_SPT5longLEXY_3-4h_1hdepletion_BlueLight_rep2
    SPT5:
      Dark:
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_3-4h_1hdepletion_Dark_rep1
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_3-4h_1hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_3-4h_1hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_3-4h_1hdepletion_BlueLight_rep2
    Pol2ser2:
      Dark:
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_3-4h_1hdepletion_Dark_rep1
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_3-4h_1hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_3-4h_1hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_3-4h_1hdepletion_BlueLight_rep2
    Pol2ser5:
      Dark:
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_3-4h_1hdepletion_Dark_rep1
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_3-4h_1hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_3-4h_1hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_3-4h_1hdepletion_BlueLight_rep2
  SPT5longLEXY_3-4h_3hdepletion:
    NELF:
      Dark:
        - SpikeInCUTnTag_NELF_SPT5longLEXY_3-4h_3hdepletion_Dark_rep1
        - SpikeInCUTnTag_NELF_SPT5longLEXY_3-4h_3hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_NELF_SPT5longLEXY_3-4h_3hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_NELF_SPT5longLEXY_3-4h_3hdepletion_BlueLight_rep2
    SPT5:
      Dark:
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_3-4h_3hdepletion_Dark_rep1
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_3-4h_3hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_3-4h_3hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_3-4h_3hdepletion_BlueLight_rep2
    Pol2ser2:
      Dark:
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_3-4h_3hdepletion_Dark_rep1
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_3-4h_3hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_3-4h_3hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_3-4h_3hdepletion_BlueLight_rep2
    Pol2ser5:
      Dark:
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_3-4h_3hdepletion_Dark_rep1
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_3-4h_3hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_3-4h_3hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_3-4h_3hdepletion_BlueLight_rep2
  SPT5longLEXY_10-12h_2hdepletion:
    NELF:
      Dark:
        - SpikeInCUTnTag_NELF_SPT5longLEXY_10-12h_2hdepletion_Dark_rep1
        - SpikeInCUTnTag_NELF_SPT5longLEXY_10-12h_2hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_NELF_SPT5longLEXY_10-12h_2hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_NELF_SPT5longLEXY_10-12h_2hdepletion_BlueLight_rep2
    SPT5:
      Dark:
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_10-12h_2hdepletion_Dark_rep1
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_10-12h_2hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_10-12h_2hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_10-12h_2hdepletion_BlueLight_rep2
    Pol2ser2:
      Dark:
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_10-12h_2hdepletion_Dark_rep1
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_10-12h_2hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_10-12h_2hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_10-12h_2hdepletion_BlueLight_rep2
    Pol2ser5:
      Dark:
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_10-12h_2hdepletion_Dark_rep1
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_10-12h_2hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_10-12h_2hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_10-12h_2hdepletion_BlueLight_rep2
  SPT5longLEXY_18-20h_2hdepletion:
    NELF:
      Dark:
        - SpikeInCUTnTag_NELF_SPT5longLEXY_18-20h_2hdepletion_Dark_rep1
        - SpikeInCUTnTag_NELF_SPT5longLEXY_18-20h_2hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_NELF_SPT5longLEXY_18-20h_2hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_NELF_SPT5longLEXY_18-20h_2hdepletion_BlueLight_rep2
    SPT5:
      Dark:
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_18-20h_2hdepletion_Dark_rep1
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_18-20h_2hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_18-20h_2hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_18-20h_2hdepletion_BlueLight_rep2
    Pol2ser2:
      Dark:
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_18-20h_2hdepletion_Dark_rep1
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_18-20h_2hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_18-20h_2hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_18-20h_2hdepletion_BlueLight_rep2
    Pol2ser5:
      Dark:
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_18-20h_2hdepletion_Dark_rep1
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_18-20h_2hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_18-20h_2hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_18-20h_2hdepletion_BlueLight_rep2
  SPT5longLEXY_18-20h_4hdepletion:
    NELF:
      Dark:
        - SpikeInCUTnTag_NELF_SPT5longLEXY_18-20h_4hdepletion_Dark_rep1
        - SpikeInCUTnTag_NELF_SPT5longLEXY_18-20h_4hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_NELF_SPT5longLEXY_18-20h_4hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_NELF_SPT5longLEXY_18-20h_4hdepletion_BlueLight_rep2
    SPT5:
      Dark:
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_18-20h_4hdepletion_Dark_rep1
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_18-20h_4hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_18-20h_4hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_SPT5_SPT5longLEXY_18-20h_4hdepletion_BlueLight_rep2
    Pol2ser2:
      Dark:
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_18-20h_4hdepletion_Dark_rep1
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_18-20h_4hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_18-20h_4hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_Pol2ser2_SPT5longLEXY_18-20h_4hdepletion_BlueLight_rep2
    Pol2ser5:
      Dark:
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_18-20h_4hdepletion_Dark_rep1
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_18-20h_4hdepletion_Dark_rep2
      BlueLight:
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_18-20h_4hdepletion_BlueLight_rep1
        - SpikeInCUTnTag_Pol2ser5_SPT5longLEXY_18-20h_4hdepletion_BlueLight_rep2



species:
  - Dmel  # Endogenous species
  - Dvir  # Exogenous species

condition_colours: # Use RGB colours. Use e.g. https://htmlcolorcodes.com   There must be as many colours as conditions
  Dark: "#0066CC" 
  BlueLight: "#666666"

annotation:
  joint_genome_fasta: /g/furlong/genome/D.melanogaster_D.virilis/Dm6_dvir-r1.07/fasta/dm6.UCSC.noMask_dvir-all-chromosome-r1.07.fa
  bwa_joint_index: /g/furlong/genome/D.melanogaster_D.virilis/Dm6_dvir-r1.07/indexes/bwa/dm6.UCSC.noMask_dvir-all-chromosome-r1.07.fa
  endo_chrsize_bed: /g/furlong/genome/D.melanogaster/Dm6/chrsizes/dm6.ucsc.chrom.sizes.bed
  exo_chrsize_bed: /g/furlong/genome/D.virilis/dvir_r1.07/chrsizes/dvir-all-chromosome-r1.07.chrsizes.bed

parameters_mapping:
  mapping:
    min_mapping_quality: 20   # Minimum mapping quality
    max_fragment_length: 2000 # maximum fragment length for mapping
  coverage_noSpikeIn:
    normalization_method: RPKM    # Normalization type for non spike-in bigwigs
    bin_size: 10              # bin size for output bigwigs
  fastq_screen:
    n_sequences: 1000000      # Numer of reads sampled from fastq files
    aligner: bowtie2          # aligner for fastq_screen (default bowtie2, other alignments require installation in config/fastq_screen.conf)
  samples_correlation:
    bin_size: 1000            # bin size for sample correlation
  spikeIn_bigwig:
    effective_genome_size: 125464728    # Mappable genome bases
    bin_size: 10              # bin size for output bigwigs
    correction_type: "exo"    # Type of correction for spike-in normalization. Must be one of: tot_reads, endo, exo, exo_by_tot

parameters_peak_calling:
  filter_bam_for_peak_calling:
    max_fragment_length: 300  # Maximum fragment length for peak calling. From exxperience, excluding large insert size reads inproves peak calling. Check that there are enough reads after filtering. 
  macs2:
    genome_size: 125464728    # Mappable genome bases
    p_value_cutoff: 0.1       # Needs to be relaxed for IDR
    input_format: BAMPE       # bam format (BAMPE for paired end)
  macs2_peak_expansion:
    size: 200                 # Summits enlargment before IDR
  IDR:
    IDR_cutoff: 0.05          # FDR cutoff for IDR
  idr_peak_expansion:
    size: 500                 # Peaks enlaargment from summit. Final peaks size will be double this. Peaks will not be overlapping (expanded only up to middle of summits)
  DESeq2:
    max_adj_pvalue: 0.01      # FDR cutoff
    min_FC: 1                 # Minimum fold change for significance
    min_reads: 10             # Minum number of reads to be considered for test
  heatmap:
    dist: 2000                # Distance from peak center fir plotHeatmap heatmaps
  peak_filtering:
    RPKM_cutoff: 25

tools:
  expand_peaks: ../../pl/expand_dhs_up_to_next.pl
  spikeIn_correction: ../../py/spikeIn_correction.py
  DESeq_bin: ../../R/DESeq2_R-4.0.0.R

heatmaps_single:
  wide: " "
  grouped: " --perGroup "
  grouped_sorted: " --perGroup --sortUsing region_length --sortRegions ascend "

heatmaps_grouped:
  grouped: " --perGroup "
  grouped_sorted: " --perGroup --sortUsing region_length --sortRegions ascend "

tss_tes: 
  TSS: "--referencePoint TSS -b 1000 -a 5000"
  TES: "--referencePoint TES -b 5000 -a 1000"
  center: "--referencePoint center -b 1000 -a 1000 --regionBodyLength 5000"
