global:
  projectpath: /g/furlong/project/92_SPT4_SPT5
  RNA-Seq_dir: RNA-Seq
  scratch_dir: /scratch/dulja/RNA-Seq_SPT4-SPT5-longLEXY
  fastq_dir: data/fastq
  qc_dir: analysis/qc
  bigwig_dir: data/bigwig
  RSEM_dir: analysis/RSEM
  DESeq_dir: analysis/DESeq
  ireads_dir: analysis/ireads


annotation:
    star: /g/furlong/genome/D.melanogaster/Dm6/indexes/STAR-2.7.9a
    rsem: /g/furlong/genome/D.melanogaster/Dm6/6.37/indices/RSEM-1.3.3_STAR-2.7.9a/dm6.UCSC
    gtf: /g/furlong/genome/D.melanogaster/Dm6/6.37/indices/RSEM-1.3.3_STAR-2.7.9a/dmel-all-r6.37.gtf
    rrna: /g/furlong/genome/D.melanogaster/Dm6/6.13/indices/STAR_RSEM/annotation/dmel-single-strand-ucsc-seqname.r6.13.rRNA.interval_list
    refflat: /g/furlong/genome/D.melanogaster/Dm6/6.13/indices/STAR_RSEM/annotation/dmel-single-strand-ucsc-seqname.r6.13.exon.ref_flat
    FBgn_name: /g/furlong/genome/D.melanogaster/Dm6/6.37/gff/FBgn_to_gene_name.txt
    intron_bed: /g/furlong/forneris/software/iread/data/intron_annotation_drosophila_ensemblv84.bed
    gene_length_file: /g/furlong/project/92_SPT4_SPT5/RNA-Seq/src/snakemake/DESEQ/gene_length_file.txt


tools:
  DESeq_bin: /g/furlong/forneris/software/DESeq2.R 
  multiqc: /g/furlong/forneris/software/Anaconda3/bin/multiqc
  fastq_screen: /g/furlong/forneris/software/FastQ-Screen-0.15.2/fastq_screen
  ireads: /g/furlong/forneris/software/iread/iread.py


RNA-Seq:
  SPT5longLEXY_3-4h:
    Dark:
      - RNA-Seq_SPT5longLEXY_3-4h_Dark_rep1: rRNA_depleion
      - RNA-Seq_SPT5longLEXY_3-4h_Dark_rep2: rRNA_depleion
    BlueLight3h:
      - RNA-Seq_SPT5longLEXY_3-4h_BlueLight1h_rep1: rRNA_depleion
      - RNA-Seq_SPT5longLEXY_3-4h_BlueLight1h_rep2: rRNA_depleion
    BlueLight1h:
      - RNA-Seq_SPT5longLEXY_3-4h_BlueLight3h_rep1: rRNA_depleion
      - RNA-Seq_SPT5longLEXY_3-4h_BlueLight3h_rep2: rRNA_depleion
  SPT5longLEXY_8-12h:
    Dark8-12h:
      - RNA-Seq_SPT5longLEXY_8-12h_Dark_rep1: polyA_selection
      - RNA-Seq_SPT5longLEXY_8-12h_Dark_rep2: polyA_selection
    BlueLight8-12h:
      - RNA-Seq_SPT5longLEXY_8-12h_BlueLight8-12h_rep1: polyA_selection
      - RNA-Seq_SPT5longLEXY_8-12h_BlueLight8-12h_rep2: polyA_selection
  SPT5longLEXY_12-16h:
    Dark12-16h:
      - RNA-Seq_SPT5longLEXY_12-16h_Dark_rep1: polyA_selection
      - RNA-Seq_SPT5longLEXY_12-16h_Dark_rep2: polyA_selection
    BlueLight8-12hDark12-16h:
      - RNA-Seq_SPT5longLEXY_12-16h_BlueLight8-12hDark12-16h_rep1: polyA_selection
      - RNA-Seq_SPT5longLEXY_12-16h_BlueLight8-12hDark12-16h_rep2: polyA_selection
    BlueLight12-16h:
      - RNA-Seq_SPT5longLEXY_12-16h_BlueLight12-16h_rep1: polyA_selection
      - RNA-Seq_SPT5longLEXY_12-16h_BlueLight12-16h_rep2: polyA_selection
  SPT5longLEXY_16-20h:
    Dark16-20h:
      - RNA-Seq_SPT5longLEXY_16-20h_Dark_rep1: polyA_selection
      - RNA-Seq_SPT5longLEXY_16-20h_Dark_rep2: polyA_selection
    BlueLight8-12hDark12-20h:
      - RNA-Seq_SPT5longLEXY_16-20h_BlueLight8-12hDark12-20h_rep1: polyA_selection
      - RNA-Seq_SPT5longLEXY_16-20h_BlueLight8-12hDark12-20h_rep2: polyA_selection
    BlueLight12-16hDark16-20h:
      - RNA-Seq_SPT5longLEXY_16-20h_BlueLight12-16hDark16-20h_rep1: polyA_selection
      - RNA-Seq_SPT5longLEXY_16-20h_BlueLight12-16hDark16-20h_rep2: polyA_selection
    BlueLight16-20h:
      - RNA-Seq_SPT5longLEXY_16-20h_BlueLight16-20h_rep1: polyA_selection
      - RNA-Seq_SPT5longLEXY_16-20h_BlueLight16-20h_rep2: polyA_selection
    BlueLight8-20h:
      - RNA-Seq_SPT5longLEXY_16-20h_BlueLight8-20h_rep1: polyA_selection
      - RNA-Seq_SPT5longLEXY_16-20h_BlueLight8-20h_rep2: polyA_selection


experiment_type_strand:
  rRNA_depleion: forward
  polyA_selection: reverse
