---
title: "Figure_4"
author: "Marvin"
date: "2024-10-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


plot_dir = "/g/furlong/project/92_SPT4_SPT5/Manuscript/Figures/Figure_4/"
```


```{r figure_4_C_vulcano_plots, comment=NA, echo=FALSE, message=FALSE, fig.height = 6, fig.width = 7}
##### This script generates all Volcano plots for the 3-4h RNA-seq data #####

### Load necessary packages
library(ggplot2)
library(dplyr)
library(readr)


options(scipen = 999)

### Functions

# Load and prepare data for a given sample
prepare_data <- function(file_path, sample_label) {
  df <- read.table(file_path, header = TRUE)
  df$gene <- rownames(df)
  df$sample <- sample_label
  return(df)
}

# Filter only significant genes based on adjusted p-value and log2 fold change
filter_significant_genes <- function(df) {
  df %>% 
    filter(padj < 0.01 & (log2FoldChange > 1 | log2FoldChange < -1)) %>% 
    dplyr::select(gene, log2FoldChange)
}

# Filter upregulated and downregulated genes
filter_regulated_genes <- function(df) {
  upregulated <- df %>% 
    filter(padj < 0.01 & log2FoldChange > 1) %>% 
    dplyr::select(gene)
  downregulated <- df %>% 
    filter(padj < 0.01 & log2FoldChange < -1) %>% 
    dplyr::select(gene)
  return(list(upregulated = upregulated, downregulated = downregulated))
}

### Volcano Plot
# List DESeq result files for all samples
file_paths <- c("/home/mayer/RNA-Seq/analysis/DESeq/SPT5longLEXY_3-4h/tables/conditionBL1h_VS_conditionDark.tsv",
                "/home/mayer/RNA-Seq/analysis/DESeq/SPT5longLEXY_3-4h/tables/conditionBL3h_VS_conditionDark.tsv")

sample_labels <- c("BL3-4h+1h", "BL3-4h+3h")

# Read data and combine into a single DataFrame
all_df <- do.call(rbind, mapply(prepare_data, file_paths, sample_labels, SIMPLIFY = FALSE))
all_df$sample <- factor(all_df$sample, levels = c("BL3-4h+1h", "BL3-4h+3h"))
all_df <- na.omit(all_df)


# Calculate statistics for the Volcano plot
calculate_statistics <- function(df) {
  df %>%
    filter(padj < 0.01 & (log2FoldChange > 1 | log2FoldChange < -1)) %>%
    group_by(sample) %>%
    summarise(total_count = n(),
              count_gt_1 = sum(log2FoldChange > 1),
              count_lt_1 = sum(log2FoldChange < -1)) %>%
    mutate(percent_gt_1 = (count_gt_1 / total_count) * 100,
           percent_lt_1 = (count_lt_1 / total_count) * 100)
}

# Prepare labels for the Volcano plot
prepare_labels <- function(stat_df, log2FoldChange) {
  stat_df %>%
    mutate(padj = 1e-250,
           pvalue = 1e-250,
           log2FoldChange = log2FoldChange)
}

create_volcano_plot <- function(df, labels_l, labels_r, output_file) {
  plot <- ggplot(df, aes(log2FoldChange, -log10(pvalue))) +
    geom_point(aes(color = case_when(
      padj < 0.01 & log2FoldChange > 1 ~ "upregulated",        # Orange for upregulated
      padj < 0.01 & log2FoldChange < -1 ~ "downregulated",     # Green for downregulated
      padj >= 0.01 & (log2FoldChange > 1 | log2FoldChange < -1) ~ "not_significant", # Gray for not significant
      TRUE ~ "constant"))) +                                   # Black for constant genes
    scale_color_manual(values = c(
      "upregulated" = "red",
      "downregulated" = "red",
      "not_significant" = "gray",
      "constant" = "gray")) +
    facet_wrap(~sample, nrow = 1) +
    #scale_x_continuous(limits = c(-5.1, 5.1)) +
    theme_classic() +
    labs(col = "Gene Regulation", 
         x = expression(log[2]('Blue Light / Dark')), 
         y = expression(-log[10](p[value]))) +
    # Hinzufügen der vertikalen, gestrichelten Linien bei log2FoldChange = 1 und log2FoldChange = -1
    geom_vline(xintercept = 1, linetype = "dashed", color = "black", size = 0.8) + 
    geom_vline(xintercept = -1, linetype = "dashed", color = "black", size = 0.8) + 
    scale_y_continuous(limits = c(0, 25)) + 
    geom_text(aes(label = count_lt_1), data = labels_l, size = 5, vjust = -0.6) +
    geom_text(aes(label = count_gt_1), data = labels_r, size = 5, vjust = -0.6) +
    theme(
      text = element_text(size = 18 , face = "bold"),   
      axis.title = element_text(size = 16, face = "plain"),         
      axis.text = element_text(size = 14, face = "plain"),              
      legend.title = element_text(size = 12, face = "plain"),           
      legend.text = element_text(size = 10, face = "plain"),             
      panel.background = element_rect(fill = "white"),
      legend.position = "none"
    ) 
  
  ggsave(filename = output_file, plot = plot, width = 8, height = 4, units = "in")
}

# Filter genes outside of x-axis limits (log2FoldChange > 5.1 or log2FoldChange < -5.1)
outside_x_limit <- all_df %>%
  filter(log2FoldChange > 5.1 | log2FoldChange < -5.1)

# Print the genes and their statistics that are outside the x-axis limits
if (nrow(outside_x_limit) > 0) {
  print("Genes outside the x-axis limits (±5.1):")
  print(outside_x_limit)
}

# Calculate statistics for Volcano plot
all_df_stat <- calculate_statistics(all_df)
tmp_labels_l <- prepare_labels(all_df_stat, -5)
tmp_labels_r <- prepare_labels(all_df_stat, 5)

# Create and save the Volcano plot with the updated color scheme
create_volcano_plot(all_df, tmp_labels_l, tmp_labels_r, paste0(plot_dir, "Figure_4_C_vulcano_plots.pdf"))

```

