channels:
    - http://hof.cluster.embl.de/bioconda
    - http://hof.cluster.embl.de/conda-forge
dependencies:
    - deeptools=3.5.5
    - bwa=0.7.17
    - cutadapt=4.1
    - samtools=1.15.1
    - picard=2.18.17
    - fastqc=0.11.9
    - multiqc=1.13
    - qualimap=2.3
    - umi_tools=1.1.6
    - fastq-screen=0.15.2
    - bowtie=1.3.1
    - bowtie2=2.4.5